# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfschema < Formula
  desc "A schema inspector for Terraform providers."
  homepage "https://github.com/minamijoyo/tfschema"
  version "0.7.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/minamijoyo/tfschema/releases/download/v0.7.1/tfschema_0.7.1_darwin_amd64.tar.gz"
      sha256 "67a41aae98b8581a05ecb64d8bf6a808a2ce6c21ad5bac976d245b4d64736cee"

      def install
        bin.install "tfschema"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/minamijoyo/tfschema/releases/download/v0.7.1/tfschema_0.7.1_linux_amd64.tar.gz"
      sha256 "d5089ce0f1d841bd00d71dc949e531e67fa5efc79c4894913326640d0c00ffb7"

      def install
        bin.install "tfschema"
      end
    end
  end

  test do
    system "#{bin}/tfschema --version"
  end
end
