# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfschema < Formula
  desc "A schema inspector for Terraform providers."
  homepage "https://github.com/minamijoyo/tfschema"
  version "0.7.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/minamijoyo/tfschema/releases/download/v0.7.2/tfschema_0.7.2_darwin_amd64.tar.gz"
      sha256 "bedcf4e7186c44c8d9d62516631ea5505a41b1c8a91562ee14cc7b635156ddfa"

      def install
        bin.install "tfschema"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/minamijoyo/tfschema/releases/download/v0.7.2/tfschema_0.7.2_linux_amd64.tar.gz"
      sha256 "cf7488b5f257f95f6ade5bbac1f59f0cbcf3c4fa105e3d48befb400730ca2078"

      def install
        bin.install "tfschema"
      end
    end
  end

  test do
    system "#{bin}/tfschema --version"
  end
end
